### PR TITLE
bump ttfautohint to v1.8.2, FreeType to 2.9.1, Harfbuzz to 1.8.4

### PR DESCRIPTION
**Pull request by chrissimpkins**

### CODE REVIEW

**Comment by anthrotype** [comment]
I had similar issues with building ttfautohint-py, because the freetype-config script is no longer installed by default, you have to pass a configure option to install that script.

Question: why not deprecate this shell script and join efforts with me in ttfautohint-py?
The latter does provide a command-line interface identical to the C++ ttfautohint binary, besides exposing a pythonic API.

**Comment by anthrotype** [comment]
i've invited you to join ttfautohint-py repo

**Comment by anthrotype** [comment]
> this script remains relevant for the Linux distros that distribute the fonts.

I'm not sure I get the connection.. Is that because they want to be able to build from source the font, and hence they also must build from source all its build requirements, such as ttfautohint itself? It doesn't make much sense to me. Why can't they use the ttfautohint version that's shipped via the distros' own package managers, and instead would need to use this script of yours?

> Are you aware of any Linux projects that are distributing ttfautohint-py?

not really, but why do you care? one can just install with pip inside a virtual environment..

**Comment by anthrotype** [comment]
> I see this as more of a build CI tool for ttfautohint against its build dependencies than anything else.

fair enough

**Comment by chrissimpkins** [comment]
> build from source the font, and hence they also must build from source all its build requirements, such as ttfautohint itself?

yep

> It doesn't make much sense to me.

agree

> Why can't they use the ttfautohint version that's shipped via the distros' own package managers, and instead would need to use this script of yours

I am not aware of how broadly ttfautohint is adopted across distros.  I believe it is on Ubuntu/Debian, don't know about Fedora.  I suspect that it is on Arch.  Very unclear and I haven't researched other commonly used distros.

> not really, but why do you care? one can just install with pip inside a virtual environment

As you've seen on the Hack repo comments, they seem to have a problem with this.  This works for individual users on a given distro, but the average user is not building from source.  My comments were about font packages that are distributed through the distro.  I suspect (maybe?) that the guidelines for free software on some of the distros would force them to rebuild your entire ttfautohint-py tool from source using a make approach like you do in the repository in order to distribute it to users as a package for installation.  This would require them to review each of the dependencies that are used in your project (if there are more than Harfbuzz and FreeType which are already in most distros if not all).  It is a lengthy review process to ensure that software is free for those distros that work under free software guidelines.  I commend them for the efforts but have to say it is a PITA to try to (1) make it happen; (2) get anything done efficiently...

**Comment by chrissimpkins** [comment]
Thanks for the link to the configure flag.  Pushed this change.  Let's see if I can get it to work :)

**Comment by chrissimpkins** [comment]
And it did!  Thanks much for your help here Cosimo.  Greatly appreciated!

**Comment by chrissimpkins** [comment]
@anthrotype btw, if you are ever interested in write permissions on this or other repos of ours/mine including this one for any reason, just ask.  More than willing to add you to ours in order to collaborate on these projects too.  I'll send you an organization invite and you can accept if you feel that there is anything that you would like write access to.  Just poke me with an email about the repos of interest if so.

**Comment by anthrotype** [comment]
Thanks!

**Pull request merged**
